<?php

global $kriesi_options;
$kriesi_options  = get_option('kriesi_options');

add_action('wp_print_scripts', 'addjquery');

function addjquery() {
	if(!is_admin())
	{
	$my_jquery = get_bloginfo('template_url'). "/js/jquery.js";
	#wp_deregister_script( 'jquery' ); 
    #wp_register_script( 'jquery', $my_jquery, false, '' ); 
	#wp_enqueue_script('jquery');
	
	$my_customJs = get_bloginfo('template_url')."/js/custom.js";
	wp_enqueue_script('my_customJs',$my_customJs,array('jquery'));
	
	$my_prettyphoto = get_bloginfo('template_url')."/prettyPhoto/js/jquery.prettyPhoto.js";
	wp_enqueue_script('prettyphoto',$my_prettyphoto,array('jquery'));
	
	$my_cufon = get_bloginfo('template_url')."/js/cufon.js";
	wp_enqueue_script('cufon',$my_cufon,array('jquery'));
	
	$my_fonts = get_bloginfo('template_url')."/js/quicksand.font.js";
	wp_enqueue_script('quicksand',$my_fonts,array('jquery'));
	
	}
}

#backend options
include(TEMPLATEPATH.'/options/import_options_no_auto_include.php');

#comment list template
include(TEMPLATEPATH.'/wp_list_comments.php');

#removes meta tag "generated by wordpress" for security purpose
function kriesi_no_generator() { return ''; }  
add_filter('the_generator','kriesi_no_generator');


class kriesi_list_post_items
{
	var $showposts;
	var $list_class_name;
	var $split_post_at;
	var $split_title_at;
	
	#constructor, change variables here
	function kriesi_list_post_items()
	{
		$this->showposts = 3;
		$this->list_class_name = "latest_news";
		$this->split_post_at = 400;
	}
	
	
	#recent posts display
	function recent_posts($heading = false)
	{	
		global $k_options;
		$alternate_bg = array('even','odd');
		$counter = 0;
		$negative_cats = preg_replace("!(\d)+!","-${0}$0", $k_options['blog']['blog_cat_final']);
		$query_string = "cat=".$negative_cats."&showposts=".$this->showposts;
		
		$rp = new WP_Query($query_string);
	

			if ($heading) echo "<h3>".$heading."</h3>";
		
			echo"<ul id='".$this->list_class_name."'>";
			
				while ($rp->have_posts()) : $rp->the_post();
				
				#shorents the comment content if too long
				
				$short_post = get_the_title();
				
	
				
				echo "<li><a href='".get_permalink()."' class='".$alternate_bg[$counter]."'>";
				
                echo'<span class="post_name">';
				echo $short_post;
                echo'</span><span class="meta"><span class="meta_sub"> ';
				the_time('d.m.Y');
				echo'</span><span class="meta_sub"> ';
				
				
				$cat_counter = 0;
				foreach((get_the_category()) as $category) 
				{	
					if ($cat_counter != 0) {echo ", ";}
     				echo $category->cat_name;
					$cat_counter++;
     			}

				echo'</span><span> ';
				comments_number('No Comments', '1 Comment', '% Comments');
				echo'</span></span></a></li>';
				$counter == 0 ? $counter = 1: $counter = 0;
				
				endwhile; 
			
			echo"</ul>";
	}	
}
